name: osumpie
description: Automate IoT using Osum Pie

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  path: ^1.7.0
  filex: ^0.2.2
  google_fonts: ^1.1.1
  dynamic_theme: ^1.0.0
  flutter_animator: ^2.1.0
  draggable_scrollbar: ^0.0.4
  font_awesome_flutter: ^8.10.0
  shared_preferences: ^0.5.12+2
  percent_indicator: "^2.1.7+2"
  linked_scroll_controller: ^0.1.2
  flutter_staggered_grid_view: ^0.3.2

  bakecode_jobs:
    path: bakecode-jobs/

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
