name: osumpie
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^1.1.1
  dynamic_theme: ^1.0.0
  flutter_animator: ^2.1.0
  gradient_widgets: ^0.5.2
  draggable_scrollbar: ^0.0.4
  shared_preferences: ^0.5.12+2
  percent_indicator: "^2.1.7+2"
  flutter_staggered_grid_view: ^0.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
